replace country = "10000" if country == "American Samoa"
replace country = "10010" if country == "Samoa, 1940-1950"
replace country = "10500" if country == "Guam"
replace country = "11000" if country == "Puerto Rico"
replace country = "11500" if country == "US Virgin Islands"
replace country = "11510" if country == "St Croix"
replace country = "11520" if country == "St John"
replace country = "11530" if country == "St Thomas"
replace country = "12000" if country == "Other US Possessions"
replace country = "12010" if country == "Johnston Atoll"
replace country = "12020" if country == "Midway Islands"
replace country = "12030" if country == "Wake Island"
replace country = "12040" if country == "Other US Caribbean Is"
replace country = "12041" if country == "Navassa Island"
replace country = "12050" if country == "Other US Pacific Is"
replace country = "12051" if country == "Baker Island"
replace country = "12052" if country == "Howland Island"
replace country = "12053" if country == "Jarvis Island"
replace country = "12054" if country == "Kingman Reef"
replace country = "12055" if country == "Palmyra Atoll"
replace country = "12090" if country == "US outlying areas"
replace country = "12091" if country == "US possessions"
replace country = "12092" if country == "US territory"
replace country = "15000" if country == "Canada"
replace country = "15010" if country == "English Canada"
replace country = "15011" if country == "British Columbia"
replace country = "15013" if country == "Alberta"
replace country = "15015" if country == "Saskatchewan"
replace country = "15017" if country == "Northwest"
replace country = "15019" if country == "Rupert's Land"
replace country = "15020" if country == "Manitoba"
replace country = "15021" if country == "Red River"
replace country = "15030" if country == "Ontario"
replace country = "15031" if country == "Upper Canada"
replace country = "15032" if country == "Canada West"
replace country = "15040" if country == "New Brunswick"
replace country = "15050" if country == "Nova Scotia"
replace country = "15051" if country == "Cape Breton"
replace country = "15052" if country == "Halifax"
replace country = "15060" if country == "Prince Edward Island"
replace country = "15070" if country == "Newfoundland"
replace country = "15080" if country == "French Canada"
replace country = "15081" if country == "Quebec"
replace country = "15082" if country == "Lower Canada"
replace country = "15083" if country == "Canada East"
replace country = "15500" if country == "St Pierre and Miquelon"
replace country = "16000" if country == "Atlantic Islands"
replace country = "16010" if country == "Bermuda"
replace country = "16020" if country == "Cape Verde"
replace country = "16030" if country == "Falkland Islands"
replace country = "16040" if country == "Greenland"
replace country = "16050" if country == "St Helena and Ascension"
replace country = "16060" if country == "Canary Islands"
replace country = "19900" if country == "North America "
replace country = "20000" if country == "Mexico"
replace country = "21000" if country == "Central America"
replace country = "21010" if country == "Belize/British Honduras"
replace country = "21020" if country == "Costa Rica"
replace country = "21030" if country == "El Salvador"
replace country = "21040" if country == "Guatemala"
replace country = "21050" if country == "Honduras"
replace country = "21060" if country == "Nicaragua"
replace country = "21070" if country == "Panama"
replace country = "21071" if country == "Canal Zone"
replace country = "21090" if country == "Central America"
replace country = "25000" if country == "Cuba"
replace country = "26000" if country == "West Indies"
replace country = "26010" if country == "Dominican Republic"
replace country = "26020" if country == "Haiti"
replace country = "26030" if country == "Jamaica"
replace country = "26040" if country == "British West Indies"
replace country = "26041" if country == "Anguilla"
replace country = "26042" if country == "Antigua-Barbuda"
replace country = "26043" if country == "Bahamas"
replace country = "26044" if country == "Barbados"
replace country = "26045" if country == "British Virgin Islands"
replace country = "26046" if country == "Anegada"
replace country = "26047" if country == "Cooper"
replace country = "26048" if country == "Jost Van Dyke"
replace country = "26049" if country == "Peter"
replace country = "26050" if country == "Tortola"
replace country = "26051" if country == "Virgin Gorda"
replace country = "26052" if country == "British Virgin Islands"
replace country = "26053" if country == "Cayman Isles"
replace country = "26054" if country == "Dominica"
replace country = "26055" if country == "Grenada"
replace country = "26056" if country == "Montserrat"
replace country = "26057" if country == "St Kitts-Nevis"
replace country = "26058" if country == "St Lucia"
replace country = "26059" if country == "St Vincent"
replace country = "26060" if country == "Trinidad and Tobago"
replace country = "26061" if country == "Turks and Caicos"
replace country = "26069" if country == "British West Indies"
replace country = "26070" if country == "Other West Indies"
replace country = "26071" if country == "Aruba"
replace country = "26072" if country == "Netherlands Antilles"
replace country = "26073" if country == "Bonaire"
replace country = "26074" if country == "Curacao"
replace country = "26075" if country == "Dutch St Maarten"
replace country = "26076" if country == "Saba"
replace country = "26077" if country == "St Eustatius"
replace country = "26079" if country == "Dutch Caribbean"
replace country = "26080" if country == "French St Maarten"
replace country = "26081" if country == "Guadeloupe"
replace country = "26082" if country == "Martinique"
replace country = "26083" if country == "St Barthelemy"
replace country = "26089" if country == "French Caribbean"
replace country = "26090" if country == "Antilles"
replace country = "26091" if country == "Caribbean "
replace country = "26092" if country == "Latin America"
replace country = "26093" if country == "Leeward Islands"
replace country = "26094" if country == "West Indies"
replace country = "26095" if country == "Windward Islands"
replace country = "29900" if country == "Americas"
replace country = "30000" if country == "SOUTH AMERICA"
replace country = "30005" if country == "Argentina"
replace country = "30010" if country == "Bolivia"
replace country = "30015" if country == "Brazil"
replace country = "30020" if country == "Chile"
replace country = "30025" if country == "Colombia"
replace country = "30030" if country == "Ecuador"
replace country = "30035" if country == "French Guiana"
replace country = "30040" if country == "Guyana/British Guiana"
replace country = "30045" if country == "Paraguay"
replace country = "30050" if country == "Peru"
replace country = "30055" if country == "Suriname"
replace country = "30060" if country == "Uruguay"
replace country = "30065" if country == "Venezuela"
replace country = "30090" if country == "South America"
replace country = "30091" if country == "South and Central America"
replace country = "40000" if country == "Denmark"
replace country = "40010" if country == "Faroe Islands"
replace country = "40100" if country == "Finland"
replace country = "40200" if country == "Iceland"
replace country = "40300" if country == "Lapland"
replace country = "40400" if country == "Norway"
replace country = "40410" if country == "Svalbard and Jan Meyen"
replace country = "40411" if country == "Svalbard"
replace country = "40412" if country == "Jan Meyen"
replace country = "40500" if country == "Sweden"
replace country = "41000" if country == "England"
replace country = "41010" if country == "Channel Islands"
replace country = "41011" if country == "Guernsey"
replace country = "41012" if country == "Jersey"
replace country = "41020" if country == "Isle of Man"
replace country = "41100" if country == "Scotland"
replace country = "41200" if country == "Wales"
replace country = "41300" if country == "United Kingdom"
replace country = "41400" if country == "Ireland"
replace country = "41410" if country == "Northern Ireland"
replace country = "41900" if country == "Northern Europe"
replace country = "42000" if country == "Belgium"
replace country = "42100" if country == "France"
replace country = "42110" if country == "Alsace-Lorraine"
replace country = "42111" if country == "Alsace"
replace country = "42112" if country == "Lorraine"
replace country = "42200" if country == "Liechtenstein"
replace country = "42300" if country == "Luxembourg"
replace country = "42400" if country == "Monaco"
replace country = "42500" if country == "Netherlands"
replace country = "42600" if country == "Switzerland"
replace country = "42900" if country == "Western Europe"
replace country = "43000" if country == "Albania"
replace country = "43100" if country == "Andorra"
replace country = "43200" if country == "Gibraltar"
replace country = "43300" if country == "Greece"
replace country = "43310" if country == "Dodecanese Islands"
replace country = "43320" if country == "Turkey Greece"
replace country = "43330" if country == "Macedonia"
replace country = "43400" if country == "Italy"
replace country = "43500" if country == "Malta"
replace country = "43600" if country == "Portugal"
replace country = "43610" if country == "Azores"
replace country = "43620" if country == "Madeira Islands"
replace country = "43630" if country == "Cape Verde Islands"
replace country = "43640" if country == "St Miguel"
replace country = "43700" if country == "San Marino"
replace country = "43800" if country == "Spain"
replace country = "43900" if country == "Vatican City"
replace country = "44000" if country == "Southern Europe"
replace country = "45000" if country == "Austria"
replace country = "45010" if country == "Austria-Hungary"
replace country = "45020" if country == "Austria-Graz"
replace country = "45030" if country == "Austria-Linz"
replace country = "45040" if country == "Austria-Salzburg"
replace country = "45050" if country == "Austria-Tyrol"
replace country = "45060" if country == "Austria-Vienna"
replace country = "45070" if country == "Austria-Kaernten"
replace country = "45080" if country == "Austria-Neustadt"
replace country = "45100" if country == "Bulgaria"
replace country = "45200" if country == "Czechoslovakia"
replace country = "45210" if country == "Bohemia"
replace country = "45211" if country == "Bohemia-Moravia"
replace country = "45212" if country == "Slovakia"
replace country = "45213" if country == "Czech Republic"
replace country = "45300" if country == "Germany"
replace country = "45301" if country == "Berlin"
replace country = "45302" if country == "West Berlin"
replace country = "45303" if country == "East Berlin"
replace country = "45310" if country == "West Germany"
replace country = "45311" if country == "Baden"
replace country = "45312" if country == "Bavaria"
replace country = "45313" if country == "Braunschweig"
replace country = "45314" if country == "Bremen"
replace country = "45315" if country == "Hamburg"
replace country = "45316" if country == "Hanover"
replace country = "45317" if country == "Hessen"
replace country = "45318" if country == "Hesse-Nassau"
replace country = "45319" if country == "Lippe"
replace country = "45320" if country == "Lubeck"
replace country = "45321" if country == "Oldenburg"
replace country = "45322" if country == "Rhineland"
replace country = "45323" if country == "Schaumburg-Lippe"
replace country = "45324" if country == "Schleswig"
replace country = "45325" if country == "Sigmaringen"
replace country = "45327" if country == "Westphalia"
replace country = "45328" if country == "Wurttemberg"
replace country = "45329" if country == "Waldecker"
replace country = "45330" if country == "Wittenberg"
replace country = "45331" if country == "Frankfurt"
replace country = "45332" if country == "Saarland"
replace country = "45333" if country == "Nordheim-Westfalen"
replace country = "45340" if country == "East Germany"
replace country = "45341" if country == "Anhalt"
replace country = "45342" if country == "Brandenburg"
replace country = "45344" if country == "Kingdom of Saxony"
replace country = "45345" if country == "Mecklinburg"
replace country = "45346" if country == "Saxony"
replace country = "45347" if country == "Thuringian States"
replace country = "45350" if country == "Probable Saxony"
replace country = "45351" if country == "Schwerin"
replace country = "45353" if country == "Probably Thuringian States"
replace country = "45360" if country == "Prussia"
replace country = "45361" if country == "Hohenzollern"
replace country = "45362" if country == "Niedersachsen"
replace country = "45400" if country == "Hungary"
replace country = "45500" if country == "Poland"
replace country = "45510" if country == "Austrian Poland"
replace country = "45511" if country == "Galicia"
replace country = "45520" if country == "German Poland"
replace country = "45521" if country == "East Prussia"
replace country = "45522" if country == "Pomerania"
replace country = "45523" if country == "Posen"
replace country = "45524" if country == "Prussian Poland"
replace country = "45525" if country == "Silesia"
replace country = "45526" if country == "West Prussia"
replace country = "45530" if country == "Russian Poland"
replace country = "45600" if country == "Romania"
replace country = "45610" if country == "Transylvania"
replace country = "45700" if country == "Yugoslavia"
replace country = "45710" if country == "Croatia"
replace country = "45720" if country == "Montenegro"
replace country = "45730" if country == "Serbia"
replace country = "45740" if country == "Bosnia"
replace country = "45750" if country == "Dalmatia"
replace country = "45760" if country == "Slovonia"
replace country = "45770" if country == "Carniola"
replace country = "45780" if country == "Slovenia"
replace country = "45790" if country == "Kosovo"
replace country = "45800" if country == "Central Europe"
replace country = "45900" if country == "Eastern Europe"
replace country = "46000" if country == "Estonia"
replace country = "46100" if country == "Latvia"
replace country = "46200" if country == "Lithuania"
replace country = "46300" if country == "Baltic States"
replace country = "46500" if country == "Russia"
replace country = "46510" if country == "Byelorussia"
replace country = "46520" if country == "Moldavia"
replace country = "46521" if country == "Bessarabia"
replace country = "46530" if country == "Ukraine"
replace country = "46540" if country == "Armenia"
replace country = "46541" if country == "Azerbaijan"
replace country = "46542" if country == "Republic of Georgia"
replace country = "46543" if country == "Kazakhstan"
replace country = "46544" if country == "Kirghizia"
replace country = "46545" if country == "Tadzhik"
replace country = "46546" if country == "Turkmenistan"
replace country = "46547" if country == "Uzbekistan"
replace country = "46548" if country == "Siberia"
replace country = "46590" if country == "USSR"
replace country = "49900" if country == "Europe"
replace country = "50000" if country == "China"
replace country = "50010" if country == "Hong Kong"
replace country = "50020" if country == "Macau"
replace country = "50030" if country == "Mongolia"
replace country = "50040" if country == "Taiwan"
replace country = "50100" if country == "Japan"
replace country = "50200" if country == "Korea"
replace country = "50210" if country == "North Korea"
replace country = "50220" if country == "South Korea"
replace country = "50900" if country == "East Asia"
replace country = "51000" if country == "Brunei"
replace country = "51100" if country == "Cambodia"
replace country = "51100" if country == "Kampuchea"
replace country = "51200" if country == "Indonesia"
replace country = "51210" if country == "East Indies"
replace country = "51220" if country == "East Timor"
replace country = "51300" if country == "Laos"
replace country = "51400" if country == "Malaysia"
replace country = "51500" if country == "Philippines"
replace country = "51600" if country == "Singapore"
replace country = "51700" if country == "Thailand"
replace country = "51800" if country == "Vietnam"
replace country = "51900" if country == "Southeast Asia"
replace country = "51910" if country == "Indochina"
replace country = "52000" if country == "Afghanistan"
replace country = "52100" if country == "India"
replace country = "52110" if country == "Bangladesh"
replace country = "52120" if country == "Bhutan"
replace country = "52130" if country == "Burma"
replace country = "52130" if country == "Myanmar"
replace country = "52140" if country == "Pakistan"
replace country = "52150" if country == "Sri Lanka"
replace country = "52150" if country == "Ceylon"
replace country = "52200" if country == "Iran"
replace country = "52300" if country == "Maldives"
replace country = "52400" if country == "Nepal"
replace country = "53000" if country == "Bahrain"
replace country = "53100" if country == "Cyprus"
replace country = "53200" if country == "Iraq"
replace country = "53210" if country == "Mesopotamia"
replace country = "53300" if country == "Iraq/Saudi Arabia"
replace country = "53400" if country == "Israel/Palestine"
replace country = "53410" if country == "Gaza Strip"
replace country = "53420" if country == "Palestine"
replace country = "53430" if country == "West Bank"
replace country = "53440" if country == "Israel"
replace country = "53500" if country == "Jordan"
replace country = "53600" if country == "Kuwait"
replace country = "53700" if country == "Lebanon"
replace country = "53800" if country == "Oman"
replace country = "53900" if country == "Qatar"
replace country = "54000" if country == "Saudi Arabia"
replace country = "54100" if country == "Syria"
replace country = "54200" if country == "Turkey"
replace country = "54210" if country == "European Turkey"
replace country = "54220" if country == "Asian Turkey"
replace country = "54300" if country == "United Arab Emirates"
replace country = "54400" if country == "Yemen Arab Republic"
replace country = "54500" if country == "Yemen"
replace country = "54600" if country == "Persia"
replace country = "54700" if country == "Middle East"
replace country = "54800" if country == "Southwest Asia"
replace country = "54900" if country == "Asia Minor"
replace country = "55000" if country == "South Asia"
replace country = "59900" if country == "Asia"
replace country = "60000" if country == "AFRICA"
replace country = "60010" if country == "Northern Africa"
replace country = "60011" if country == "Algeria"
replace country = "60012" if country == "Egypt"
replace country = "60013" if country == "Libya"
replace country = "60014" if country == "Morocco"
replace country = "60015" if country == "Sudan"
replace country = "60016" if country == "Tunisia"
replace country = "60017" if country == "Western Sahara"
replace country = "60019" if country == "North Africa"
replace country = "60020" if country == "Benin"
replace country = "60021" if country == "Burkina Faso"
replace country = "60022" if country == "Gambia"
replace country = "60023" if country == "Ghana"
replace country = "60024" if country == "Guinea"
replace country = "60025" if country == "Guinea-Bissau"
replace country = "60026" if country == "Ivory Coast"
replace country = "60027" if country == "Liberia"
replace country = "60028" if country == "Mali"
replace country = "60029" if country == "Mauritania"
replace country = "60030" if country == "Niger"
replace country = "60031" if country == "Nigeria"
replace country = "60032" if country == "Senegal"
replace country = "60033" if country == "Sierra Leone"
replace country = "60034" if country == "Togo"
replace country = "60038" if country == "Western Africa"
replace country = "60039" if country == "French West Africa"
replace country = "60040" if country == "British Indian Ocean Territory"
replace country = "60041" if country == "Burundi"
replace country = "60042" if country == "Comoros"
replace country = "60043" if country == "Djibouti"
replace country = "60044" if country == "Ethiopia"
replace country = "60045" if country == "Kenya"
replace country = "60046" if country == "Madagascar"
replace country = "60047" if country == "Malawi"
replace country = "60048" if country == "Mauritius"
replace country = "60049" if country == "Mozambique"
replace country = "60050" if country == "Reunion"
replace country = "60051" if country == "Rwanda"
replace country = "60052" if country == "Seychelles"
replace country = "60053" if country == "Somalia"
replace country = "60054" if country == "Tanzania"
replace country = "60055" if country == "Uganda"
replace country = "60056" if country == "Zambia"
replace country = "60057" if country == "Zimbabwe"
replace country = "60058" if country == "Bassas da India"
replace country = "60059" if country == "Europa"
replace country = "60060" if country == "Gloriosos"
replace country = "60061" if country == "Juan de Nova"
replace country = "60062" if country == "Mayotte"
replace country = "60063" if country == "Tromelin"
replace country = "60064" if country == "Eastern Africa"
replace country = "60065" if country == "Eritrea"
replace country = "60070" if country == "Central Africa"
replace country = "60071" if country == "Angola"
replace country = "60072" if country == "Cameroon"
replace country = "60073" if country == "Central African Republic"
replace country = "60074" if country == "Chad"
replace country = "60075" if country == "Congo"
replace country = "60076" if country == "Equatorial Guinea"
replace country = "60077" if country == "Gabon"
replace country = "60078" if country == "Sao Tome and Principe"
replace country = "60079" if country == "Zaire"
replace country = "60080" if country == "Central Africa"
replace country = "60081" if country == "Equatorial Africa"
replace country = "60082" if country == "French Equatorial Africa"
replace country = "60090" if country == "Southern Africa"
replace country = "60091" if country == "Botswana"
replace country = "60092" if country == "Lesotho"
replace country = "60093" if country == "Namibia"
replace country = "60094" if country == "South Africa"
replace country = "60095" if country == "Swaziland"
replace country = "60096" if country == "Southern Africa"
replace country = "60099" if country == "Africa"
replace country = "70000" if country == "Australia and New Zealand"
replace country = "70010" if country == "Australia"
replace country = "70011" if country == "Ashmore and Cartier Islands"
replace country = "70012" if country == "Coral Sea Islands Territory"
replace country = "70013" if country == "Christmas Island"
replace country = "70014" if country == "Cocos Islands"
replace country = "70020" if country == "New Zealand"
replace country = "71000" if country == "Pacific Islands"
replace country = "71010" if country == "New Caledonia"
replace country = "71012" if country == "Papua New Guinea"
replace country = "71013" if country == "Solomon Islands"
replace country = "71014" if country == "Vanuatu (New Hebrides)"
replace country = "71015" if country == "Fiji"
replace country = "71016" if country == "Melanesia"
replace country = "71017" if country == "Norfolk Islands"
replace country = "71018" if country == "Niue"
replace country = "71020" if country == "Cook Islands"
replace country = "71022" if country == "French Polynesia"
replace country = "71023" if country == "Tonga"
replace country = "71024" if country == "Wallis and Futuna Islands"
replace country = "71025" if country == "Western Samoa"
replace country = "71026" if country == "Pitcairn Island"
replace country = "71027" if country == "Tokelau"
replace country = "71028" if country == "Tuvalu"
replace country = "71029" if country == "Polynesia"
replace country = "71032" if country == "Kiribati"
replace country = "71033" if country == "Canton and Enderbury"
replace country = "71034" if country == "Nauru"
replace country = "71039" if country == "Micronesia"
replace country = "71040" if country == "US Pacific Trust Territories"
replace country = "71041" if country == "Marshall Islands"
replace country = "71042" if country == "Micronesia"
replace country = "71043" if country == "Kosrae"
replace country = "71044" if country == "Pohnpei"
replace country = "71045" if country == "Truk"
replace country = "71046" if country == "Yap"
replace country = "71047" if country == "Northern Mariana Islands"
replace country = "71048" if country == "Palau"
replace country = "71049" if country == "Pacific Trust Territories"
replace country = "71050" if country == "Clipperton Island"
replace country = "71090" if country == "Oceania"
replace country = "80000" if country == "ANTARTICA"
replace country = "80010" if country == "Bouvet Islands"
replace country = "80020" if country == "British Antarctic Terr"
replace country = "80030" if country == "Dronning Maud Land"
replace country = "80040" if country == "French Southern and Antartic Lands"
replace country = "80050" if country == "Heard and McDonald Islands"
replace country = "90000" if country == "ABROAD (unknown) or at sea"
replace country = "90010" if country == "Abroad"
replace country = "90011" if country == "Abroad (US citizen)"
replace country = "90020" if country == "At sea"
replace country = "90021" if country == "At sea (US citizen)"
replace country = "90022" if country == "At sea or abroad (US citizen)"
replace country = "95000" if country == "OTHER"
replace country = "99700" if country == "Unknown"
replace country = "99800" if country == "Illegible"
replace country = "99900" if country == "Missing/blank"
compress country
destring country, replace force
label values country bpl_lbl
