replace state = "01" if state == "Alabama"
replace state = "02" if state == "Alaska"
replace state = "04" if state == "Arizona"
replace state = "05" if state == "Arkansas"
replace state = "06" if state == "California"
replace state = "08" if state == "Colorado"
replace state = "09" if state == "Connecticut"
replace state = "10" if state == "Delaware"
replace state = "11" if state == "District of Columbia"
replace state = "12" if state == "Florida"
replace state = "13" if state == "Georgia"
replace state = "15" if state == "Hawaii"
replace state = "16" if state == "Idaho"
replace state = "17" if state == "Illinois"
replace state = "18" if state == "Indiana"
replace state = "19" if state == "Iowa"
replace state = "20" if state == "Kansas"
replace state = "21" if state == "Kentucky"
replace state = "22" if state == "Louisiana"
replace state = "23" if state == "Maine"
replace state = "24" if state == "Maryland"
replace state = "25" if state == "Massachusetts"
replace state = "26" if state == "Michigan"
replace state = "27" if state == "Minnesota"
replace state = "28" if state == "Mississippi"
replace state = "29" if state == "Missouri"
replace state = "30" if state == "Montana"
replace state = "31" if state == "Nebraska"
replace state = "32" if state == "Nevada"
replace state = "33" if state == "New Hampshire"
replace state = "34" if state == "New Jersey"
replace state = "35" if state == "New Mexico"
replace state = "36" if state == "New York"
replace state = "37" if state == "North Carolina"
replace state = "38" if state == "North Dakota"
replace state = "39" if state == "Ohio"
replace state = "40" if state == "Oklahoma"
replace state = "41" if state == "Oregon"
replace state = "42" if state == "Pennsylvania"
replace state = "44" if state == "Rhode Island"
replace state = "45" if state == "South Carolina"
replace state = "46" if state == "South Dakota"
replace state = "47" if state == "Tennessee"
replace state = "48" if state == "Texas"
replace state = "49" if state == "Utah"
replace state = "50" if state == "Vermont"
replace state = "51" if state == "Virginia"
replace state = "53" if state == "Washington"
replace state = "54" if state == "West Virginia"
replace state = "55" if state == "Wisconsin"
replace state = "56" if state == "Wyoming"
replace state = "72" if state == "Puerto Rico"
replace state = "99" if state == "State not identified" | state == "Total"
compress state
destring state, replace force
label values state statefip_lbl
